/* Battle Tracker service worker. Generated by web/, copied into www/. */
const CACHE = "battle-tracker-v4";
const ASSETS = ["./", "./index.html", "./manifest.webmanifest",
                "./privacy.html", "./icon-192.png", "./icon-512.png", "./icon-maskable-512.png"];

self.addEventListener("install", e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(ASSETS)).then(() => self.skipWaiting()));
});

self.addEventListener("activate", e => {
  e.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", e => {
  if(e.request.method !== "GET") return;
  // Other origins (a room's Firebase traffic, the emoji font) go straight to the
  // network. Answered from here, a failed room request would get index.html back.
  if(new URL(e.request.url).origin !== self.location.origin) return;
  e.respondWith(
    caches.match(e.request).then(hit => {
      if(hit){
        // refresh in the background so the next launch is current
        fetch(e.request).then(res => {
          if(res && res.ok) caches.open(CACHE).then(c => c.put(e.request, res));
        }).catch(() => {});
        return hit;
      }
      return fetch(e.request).then(res => {
        if(res && res.ok && e.request.url.startsWith(self.location.origin)){
          const copy = res.clone();
          caches.open(CACHE).then(c => c.put(e.request, copy));
        }
        return res;
      }).catch(() => caches.match("./index.html"));
    })
  );
});
